name: fluidbuild
description: A personal OS image based on Fedora, very lightly customised.

base-image: ghcr.io/ublue-os/silverblue-main
image-version: latest

modules:
  - type: files
    files:
      - source: system
        destination: /

  - type: rpm-ostree
    install:
      - emacs
      - keepassxc
      - syncthing
      - enchant2-devel
    remove:
      - firefox
      - firefox-langpacks
      - gnome-tour
      - gnome-initial-setup

  - type: default-flatpaks
    system:
      repo-url: https://dl.flathub.org/repo/flathub.flatpakrepo
      repo-name: flathub

  - type: brew
    nofile-limits: true
    brew-analytics: false

  - type: chezmoi
    repository: https://github.com/sgbonney/dotfiles

  - type: signing
